name: PlayerSettingsMenu
version: '1.0-SNAPSHOT'
main: me.nuttist.playerSettingsMenu.core.PlayerSettingsMenu
api-version: '1.21'
commands:
  menu:
    description: A command for players to open their personal settings gui
  unhide:
    description: A command that allows players to toggle individual player invisibility.